version: '2'

services:
    redis:
        image: redis:alpine
        networks:
            - backbone

    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=example
        networks:
            - backbone

    data:
        build: .
        environment:
            - FTP_SERVER=<your_server>
            - FTP_USERNAME=<your_username>
            - FTP_PASSWORD=<your_password>
            - REDIS=redis
            - POSTGRES=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=example
            - POSTGRES_DB=postgres
        networks: 
            - backbone

networks:
  backbone:
    driver: bridge