version: '2'

services:
    redis:
        image: redis
        networks:
            - backbone

    data:
        build: .
        environment:
            - FTP_SERVER=<your_server>
            - FTP_USERNAME=<your_username>
            - FTP_PASSWORD=<your_password>
            - REDIS=redis
        networks: 
            - backbone

networks:
  backbone:
    driver: bridge