#!/bin/sh

# set -
NOW=$(date +"%d_%B_%Y_%H_%M_%S")
# source ./env
if [ -n "$REDIS" ]; then
    redis-dump -h $REDIS --json > /etc/periodic/15min/wikiredisdump_$NOW.json
fi
if [ -n "$POSTGRES" ]; then
    PGPASSWORD=$POSTGRES_PASSWORD pg_dump -U $POSTGRES_USER -d $POSTGRES_DB -h $POSTGRES > /etc/periodic/15min/wikipostgresdump_$NOW.sql
fi
if [ -n "$MONGODB" ]; then
    mongodump --host $MONGODB_HOST:$MONGODB_PORT --gzip --archive=wikibot_$NOW.archive
fi
if [ -n "$FTP_SERVER" ]; then
    ncftp <<END_OF_SESSION
    open -u $FTP_USERNAME -p $FTP_PASSWORD $FTP_SERVER
    cd backups/
    put /etc/periodic/15min/wikiredisdump_$NOW.json /etc/periodic/15min/wikipostgresdump_$NOW.sql /etc/periodic/15min/wikibot_$NOW.archive
    bye
END_OF_SESSION
fi
if [ -n "$DROPBOX" ]; then
    echo "OAUTH_ACCESS_TOKEN=$DROPBOX_ACCESS_TOKEN" > /etc/periodic/15min/.dropbox_uploader
    bash /etc/periodic/15min/dropbox_uploader.sh upload /etc/periodic/15min/wikiredisdump_$NOW.json wikiredisdump_$NOW.json
    bash /etc/periodic/15min/dropbox_uploader.sh upload /etc/periodic/15min/wikipostgresdump_$NOW.sql wikipostgresdump_$NOW.sql
    bash /etc/periodic/15min/dropbox_uploader.sh upload /etc/periodic/15min/wikibot_$NOW.archive wikibot_$NOW.archive
fi
echo "Fatto!"